name: Validate with hassfest
on:
  push:
    branches: [ main ]     # ← Only run on pushes to main
  pull_request:
    branches: [ main ]     # ← Only run on PRs targeting main
  schedule:
    - cron:  '0 0 * * *'   # ← Keep the daily schedule
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - name: Check out repository
          uses: "actions/checkout@v4"
        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
